layout_spectrum: 0.9993742
name: Polaroid SX-70
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  saturation: 0.7353644
  brandColors:
    - '#010101'
    - '#FDFDFD'
    - '#75797C'
    - '#EA672E'
    - '#7E0C09'
  lightness: 1
  rhythmicContrast: 0.7137961
typography_spectrum: 0.3785982
